### ISSUE TITLE
Flying/Dashing/Being frozen on most kaijus triggers the anticheat

### ISSUE THREAD

**Issue by vret001** [vret001/KU#32]
**Describe the bug**
Occasionally users will be teleported backwards and damaged during/after dashing, as well as when they're frozen

**When did you last experience the issue:**
2/19/22

**To Reproduce**
- Use most dashes
- Use some moves that make the player stay in place (Kumonga's dance, MZ's concentrate, etc.)

**Expected behavior**
Anticheat should not trigger

**Comment by vret001** [comment]
This seems to be a very common issue, as such perhaps a patch setting the anti cheat to be very lenient for the time being may be required.

**Comment by EnderReaper16** [comment]
Uploading Roblox 02-19-2022 9-23-23-101_Trim.mp4…

this happens when i do mg21 dash, it doesnt always happen, but it happens most of the time

**Comment by vret001** [comment]
I believed I've fixed the dashing issue, it should no longer trigger the anticheat.

**Comment by essentery** [comment]
https://user-images.githubusercontent.com/100055786/154826017-412dd241-6002-4a50-8e6b-63845f608828.mp4

The issue still happens to me just much less than it used to it usually only occurs when im a bit laggy i dont know if the fact that when i dash it trys to push me under the ground has anything to do with it

**Comment by vret001** [comment]
> I believed I've fixed the dashing issue, it should no longer trigger the anticheat.

This will be in the next update

**Comment by vret001** [comment]
This should be fixed in the latest update. Please let us know if this issue still occurs.
